### ISSUE TITLE
Supporting unknown SOPClassUID

### ISSUE THREAD

**Issue by yigitsoy** [MGHComputationalPathology/highdicom#41]
We are investigating the use of highdicom for converting our NIfTI segmentation outputs to DICOM SEG format. The corresponding DICOM series have some of the fields anonymised. For instance SOPClassUID.

It seems highdicom is expecting a predefined set of UIDs. Is there possibility of supporting also unknown fields as well?

Here is the error message I am getting;

```bash
traceback (most recent call last):
  File "convert.py", line 75, in <module>
    seg_dataset = Segmentation(
  File "/../lib/python3.8/site-packages/highdicom/seg/sop.py", line 422, in __init__
    self.copy_specimen_information(src_img)
  File "/../lib/python3.8/site-packages/highdicom/base.py", line 285, in copy_specimen_information
    self._copy_root_attributes_of_module(dataset, 'Image', 'Specimen')
  File "/../lib/python3.8/site-packages/highdicom/base.py", line 240, in _copy_root_attributes_of_module
    iod_key = SOP_CLASS_UID_IOD_KEY_MAP[dataset.SOPClassUID]
KeyError: '05703841015643452503209109170649121759226008273168'
```

**Comment by seandoyle** [comment]
What are you using to anonymize this file? The SOPClassUID shouldn't be anonymized - it identifies the type of DICOM object (MR image, CT image, GSPS object, .. &etc).[List of possible UIDs](http://dicom.nema.org/dicom/2013/output/chtml/part04/sect_B.5.html). This field should not be modified by the anonymizer.

**Comment by CPBridge** [comment]
Thanks for trying out highdicom!

A cornerstone of highdicom is conformance to the DICOM standard. Files without certain UIDs, including the SOPClassUID, do not conform to the DICOM standard. Therefore I don't think we would want to support this use case. Sorry.

As @seandoyle says, the SOPClassUID should correctly identify the type of the image and do not contain any patient information whatsoever and so there's no reason at all that an anonymization tool should remove them.

If you really need to get these specific files converted and can't use a better anonymization tool, I suggest manually correcting their SOPClassUIDs to the correct imaging modality (referencing the list @seandoyle sent) before attempting conversion. You may also need to generate new UIDs (using the `highdicom.uid.UID()` constructor.) for other UID values such as `StudyInstanceUID`, `SeriesInstanceUID`, `SOPInstanceUID` and `FrameOfReference`.

Let us know if you have any other questions or issues

**Comment by hackermd** [comment]
I agree with @seandoyle and @CPBridge. DICOM differentiates between type 1 (required, cannot be empty), type 2 (required, can be empty) and type 3 attributes (optional). `SOPClassUID` is a type 1 attribute and a DICOM data set without that attribute (or an empty value) would not be compliant with the standard. See [Part 15 Chapter E Table E.1-1](http://dicom.nema.org/medical/dicom/current/output/chtml/part15/chapter_E.html#table_E.1-1) for an overview of what attributes are supposed to be removed/modified upon de-identification.

**Comment by yigitsoy** [comment]
Thank you for your detailed explanation and sorry for my belated response. I fully agree
