### ISSUE TITLE
Should inclusion of referenced images in PertinentOtherEvidenceSequence be enforced?

### ISSUE THREAD

**Issue by CPBridge** [MGHComputationalPathology/highdicom#62]
It is my understanding that the PertinentOtherEvidenceSequence should contain all instances referenced anywhere in the content tree, and failing to do so would technically be non-compliant. See [sect_C.17.2.3](http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.17.2.3.html#sect_C.17.2.3)

> [evidence in PertinentOtherEvidenceSequence] shall include, but is not limited to, all current evidence referenced in the content tree

When constructing an SR object, highdicom has all the available information to ensure that this has been done correctly (i.e. no referenced instance in the content tree has been omitted from the `evidence` parameter), but it currently does not do so.

I would suggest that one improvement could be to add code to the SR constructor that walks the content tree and raises an exception if any evidence is missing. Unfortunately I think it will not be possible to automatically add the evidence as some information (such as series instance uid) may be missing from the references in the content tree.

Thoughts? @hackermd

**Comment by hackermd** [comment]
Good catch!

There are several aspects:

1. Recording all evidence that is referenced in the content tree.
2. Extracting the relevant information automatically from items contained in `ContentSequence` or from the passed `evidence`.
3. Deciding whether the evidence should go into `CurrentRequestedProcedureEvidenceSequence` or `PertinentOtherEvidenceSequence`.

We should be able to determine all evidence based on the value type of content items (`IMAGE`, `COMPOSITE`, etc.) passed via `content`. You are right that the `SeriesInstanceUID` is not contained in the content items, but is required to reference the SOP instances via `CurrentRequestedProcedureEvidenceSequence` or `PertinentOtherEvidenceSequence`. Therefore, the corresponding SOP instances (`pydicom.dataset.Dataset` objects) have to be passed via `evidence`. I agree with you that it would be beneficial to add checks that ensure that's actually the case.

However, we currently also use `evidence` to copy the corresponding study-level metadata. Can we assume that all SOP instances referenced in the content tree are part of the same study? @dclunie could you kindly confirm this contraint?

**Comment by hackermd** [comment]
I just realized that we probably incorrectly include references for the instances in `evidence` in `PertinentOtherEvidenceSequence`, but should rather include them in `CurrentRequestedProcedureEvidenceSequence`. See [Current Requested Procedure Evidence Sequence](http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.17.2.html#para_32fb8faf-1992-4589-95b9-589193c28f58):

> Full set of Composite SOP Instances, of which the creator is aware, which were created to satisfy the current Requested Procedure(s) for which this SR Document is generated **or that are referenced in the content tree**.

**Comment by CPBridge** [comment]
I was wondering about that too. I think that's probably more correct but I'm not sure it's 100% right either. The entry for PertinentOtherEvidenceSequence reads

> Other Composite SOP Instances that are considered to be pertinent evidence by the creator of this SR Document. This evidence must have been acquired in order to satisfy Requested Procedures other than the one(s) for which this SR Document is generated.

So I think the deciding factor is whether the evidence is part of the same Request Procedure as the SR or not, and I don't know how this relates to Study. I'm not completely sure on the definition of Requested Procedure, but what if something along the following lines happened: someone has a CT scan (one requested procedure) which gives rise to study. Some arbitrary length of time later, perhaps an AI based project, a physician (or possibly an AI model) reviews the images and generates an SR and SEG instance based on his/her/its analysis of the study. Would that be a different Requested Procedure? In which case, would the SEG instance go into Current Requested Procedure Evidence, and the original CT scan instances go into Pertinent Other Evidence when generating the SR?

**Comment by hackermd** [comment]
> So the deciding factor is whether the evidence is part of the same Requested Procedure as the SR or not, and I don't know how this relates to Study. I'm not completely sure on the definition of Requested Procedure, but what if something along the following lines happened: someone has a CT scan (one requested procedure) which gives rise to study. Some arbitrary length of time later, a physician (or possibly an AI model) reviews the images and generates an SR and SEG instance based on his/her/its analysis of the study. Would that be a different Requested Procedure? In which case, would the SEG instance go into Current Requested Procedure Evidence, and the original CT scan instances go into Pertinent Other Evidence when generating the SR?

Excellent questions! I don't know to be honest. It would be worth discussing with @dclunie, @seandoyle, @fedorov and @pieper.

**Comment by pieper** [comment]
Yes, very important things to sort out.  I don't know the exact answer but I think you are on the right track and would be glad to discuss.

**Comment by CPBridge** [comment]
This issue was closed by #67
