### ISSUE TITLE
Content item for Person Observer Name in template Person Observer Identifying Attributes has wrong value type

### ISSUE THREAD

**Issue by hackermd** [MGHComputationalPathology/highdicom#76]
I just realized that [Person Observer Name](http://dicom.nema.org/medical/dicom/current/output/chtml/part16/chapter_A.html#para_3d762f92-f577-429e-9fa5-3c4f635bd9f4) is currently incorrectly encoded using `TextContentItem` instead of `PnameContentItem` (see [highdicom.sr.templates.PersonObserverIdentifyingAttributes](https://github.com/MGHComputationalPathology/highdicom/blob/b378a20a23a62a55ef2614377465a034c42eb128/src/highdicom/sr/templates.py#L532)).

**Comment by fedorov** [comment]
I came across this too, and thought that I am doing something incorrectly!

**Comment by CPBridge** [comment]
Resolved in #75
