### ISSUE TITLE
Creating segmentation is slow when using a large number of segments

### ISSUE THREAD

**Issue by cgorman** [MGHComputationalPathology/highdicom#81]
Spoke with @hackermd about this earlier. I am trying to save a feature vector for each frame of a SM image as a segmentation which ends up creating 1024 segments. I pinned the slowness down to [these lines](https://github.com/MGHComputationalPathology/highdicom/blob/1a904e58bc3685eef190e626a0052a21831d8168/src/highdicom/utils.py#L213-L232).

**Comment by hackermd** [comment]
Thanks @cgorman for reporting the issue. It should be fixed (i.e., the performance should be improved) by 9d0210b397640559408fc675d667414bf3b68f83
