### ISSUE TITLE
Is it possible to create a dicomseg for a DX?

### ISSUE THREAD

**Issue by a-parida12** [MGHComputationalPathology/highdicom#99]
I am trying to save the segmentation of a CXR as a dicomseg. 
```
seg_dataset = Segmentation(
            source_images=[source_image],
            pixel_array=np.uint16(seg_img),
            segmentation_type=SegmentationTypeValues.FRACTIONAL,
            segment_descriptions=description_segments,
            series_instance_uid=generate_uid(),
            sop_instance_uid=generate_uid(),
            instance_number=instance_number,
            manufacturer="deepc",
            manufacturer_model_name=config["NAME"],
            software_versions="v"+config["VERSION"],
            device_serial_number="Device XYZ",
            series_number=2,
            fractional_type="OCCUPANCY",
        )
```

Even though I am using a proper `DX` dcm. I am getting errors where it says some fields like `StudyID`, `SliceThickness` and `PixelSpacing` are missing in the `source_image`. Is it possible to skip the missing fields? or is there a better way to handle such scenarios?

**Comment by hackermd** [comment]
Thanks @a-parida12 for your interest in the library and for reporting the issue.

The *Slice Thickness* and *Pixel Spacing* attributes are required for creation of a Segmentation instance (see [Pixel Measures Macro Attributes](http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.7.6.16.2.html#sect_C.7.6.16.2.1)).

Interestingly, the *Pixel Spacing* attribute has type 1C in case of a Diagnostic X-Ray Image (see [Basic Pixel Spacing Calibration Macro Attributes](http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_10.7.html#table_10-10)) and I am not sure whether *Slice Thickness* may be present.

You can provide this information to the constructor of `highdicom.seg.Segmentation` using the `pixel_measures` parameter (see [highdicom.seg.Segmentation](https://highdicom.readthedocs.io/en/latest/package.html#highdicom.seg.Segmentation)).

The *Study ID* attribute is type 2, so it should be present in the source image even if it does not have a value. You could just patch the `source_image` prior to passing it to `highdicom.seg.Segmentation`:

```python
source_image.StudyID = None
pixel_measures = PixelMeasuresSequence(
    pixel_spacing=...,
    slice_thickness=...,
)

seg_dataset = Segmentation(
    source_images=[source_image],
    pixel_array=np.uint16(seg_img),
    segmentation_type=SegmentationTypeValues.FRACTIONAL,
    segment_descriptions=description_segments,
    series_instance_uid=generate_uid(),
    sop_instance_uid=generate_uid(),
    instance_number=instance_number,
    manufacturer="deepc",
    manufacturer_model_name=config["NAME"],
    software_versions="v"+config["VERSION"],
    device_serial_number="Device XYZ",
    series_number=2,
    fractional_type="OCCUPANCY",
    pixel_measures=pixel_measures
)
```

**Comment by hackermd** [comment]
Closing the issue due to inactivity.
